spring.profiles.active=dev

spring.application.name=platzi-Play
server.servlet.context-path=/platzi-play/api

#spring Data jpa
spring.datasource.driver-class-name=org.postgresql.Driver


#langchain4j
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini