server.port=8090

#spring Data jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/platziplay
spring.datasource.username=angel
spring.datasource.password=platzi

# actualiza el esquema segn sea necesario.
spring.jpa.hibernate.ddl-auto=update
# muestra en consola las operaciones SQL que ejecuta la aplicacin.
spring.jpa.show-sql=true
# formatea el SQL para facilitar la lectura.
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# langchain4j
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open_ai.chat-model.log-requests=true
langchain4j.open_ai.chat-model.log-responses=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG